"""empty message

Revision ID: 33caefdbdb99
Revises: 6e7883366500
Create Date: 2023-10-29 00:28:08.391251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '33caefdbdb99'
down_revision = '6e7883366500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'interest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('interest', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
