"""empty message

Revision ID: 6e7883366500
Revises: 
Create Date: 2023-10-29 00:17:57.119986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7883366500'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('user_pw', sa.String(), nullable=False),
    sa.Column('major', sa.String(), nullable=False),
    sa.Column('interest', sa.JSON(), nullable=True),
    sa.Column('empty_times', sa.JSON(), nullable=True),
    sa.Column('subjects', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
