"""empty message

Revision ID: b3343d814521
Revises: 6c760092ce8b
Create Date: 2023-10-29 03:28:28.308695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3343d814521'
down_revision = '6c760092ce8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_empty_time_id'), 'empty_time', ['id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_empty_time_id'), table_name='empty_time')
    # ### end Alembic commands ###
